services:
  eventsmanager:
    image: postgres:latest
    container_name: eventsmanager
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: eventsmanager
        POSTGRES_DB: eventsmanager
        POSTGRES_USER: eventsmanager