module.exports = {
    up: async (queryInterface, Sequelize) => queryInterface.bulkInsert('events', [
      {
        actualCountry: 'chile',
        eventType: '0',
        adults: true,
        ageRange: '',
        name: 'Glup en Vivo - Lanzamiento Nuevo Disco - Trotamundos Quilpué (+18)',
        artists: 'Glup!',
        description: 'Glup en Vivo Lanzamiento Nuevo Disco Trotamundos Quilpué Sabado 2 de Diciembre Acceso 21:00hrsShow 22:00hrsESPACIO CERRADO, NO SE PUEDE FUMAR!.',
        startDate: '2023-12-02',
        startHour: '21:00',
        endDate: '2023',
        endHour: '',
        region: '',
        commune: '',
        address: 'Trotamundos Terraza Anibal Pinto 879',
        place: 'Trotamundos Terraza',
        urlVideo: '',
        img_url: 'https://res.cloudinary.com/drgcrjsax/image/upload/v1693788689/mzxdleynsfeje3m1ygqm.jpg',
        img_public_id:'mzxdleynsfeje3m1ygqm',
        conditionTerms: true,
        producerId : 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        actualCountry: 'chile',
        eventType: '0',
        adults: true,
        ageRange: '',
        name: 'Javier Barría en Trotamundos Terraza (+18)',
        artists: 'Javiera Barría',
        description: 'Tras su exitoso paso por el Festival Internacional Womad Chile y luego de recibir el premio Pulsar 2023 como mejor productor, Javier Barría vuelve a salir de gira presentando un concierto de reencuentro en donde podrán escuchar una dedicada selección de todos sus discos y disfrutar de un formato intimo y cercano!Las entradas de Meet & Greet incluyen un encuentro con Javier previo al concierto con una copia de Estación Pirque o Folclor firmada',
        startDate: '2023-11-16',
        startHour: '21:00',
        endDate: '',
        endHour: '',
        region: '',
        commune: '',
        address: 'Trotamundos Terraza Anibal Pinto 879',
        place: 'Trotamundos Terraza',
        urlVideo: '',
        img_url: 'https://res.cloudinary.com/drgcrjsax/image/upload/v1693279360/lxefjtk73sczgpxsxut3.jpg',
        img_public_id:'lxefjtk73sczgpxsxut3',
        conditionTerms: true,
        producerId : 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        actualCountry: 'chile',
        eventType: '0',
        adults: true,
        ageRange: '',
        name: 'Alex Anwandter - El Diablo En El Cuerpo En Vivo - Trotamundos Quilpué (+18)',
        artists: 'Alex Andwandter',
        description: 'Alex Anwandter en VivoEl Diablo En El CuerpoTrotamundos QuilpuéSabado 21 de OctubreAcceso 21:00hrsShow 22:00hrsESPACIO CERRADO, NO SE PUEDE FUMAR!.',
        startDate: '2023-10-21',
        startHour: '21:00',
        endDate: '',
        endHour: '',
        region: '',
        commune: '',
        address: 'Trotamundos Terraza Anibal Pinto 879',
        place: 'Trotamundos Terraza',
        urlVideo: '',
        img_url: 'https://res.cloudinary.com/drgcrjsax/image/upload/v1693272635/jnclcwmiwlzjsxbrgjc3.jpg',
        img_public_id:'jnclcwmiwlzjsxbrgjc3',
        conditionTerms: true,
        producerId : 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        actualCountry: 'chile',
        eventType: '0',
        adults: true,
        ageRange: '',
        name: 'Cristóbal Briceño y el Grupo Crisis en vivo',
        artists: 'Cristóbal Briceño',
        description: 'Cristóbal Briceño y el Grupo Crisis por primera vez en la quinta región!',
        startDate: '2023-07-30',
        startHour: '20:00',
        endDate: '',
        endHour: '',
        region: '',
        commune: '',
        address: 'Trotamundos Terraza Anibal Pinto 879',
        place: 'Trotamundos Terraza',
        urlVideo: '',
        img_url: 'https://res.cloudinary.com/drgcrjsax/image/upload/v1693279174/gklimagxuecffhmbgbwf.jpg',
        img_public_id:'gklimagxuecffhmbgbwf',
        conditionTerms: true,
        producerId : 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        actualCountry: 'chile',
        eventType: '0',
        adults: true,
        ageRange: '',
        name: 'Moral Distraída en Trotamundos Quilpué (+18)',
        artists: 'Moral Distraida',
        description: 'Moral Distraida en VivoTrotamundos QuilpuéViernes 28 de JulioAcceso 21:00hrsShow 22:30hrsESPACIO CERRADO, NO SE PUEDE FUMAR!.',
        startDate: '2023-07-28',
        startHour: '21:30',
        endDate: '',
        endHour: '',
        region: '',
        commune: '',
        address: 'Trotamundos Terraza Anibal Pinto 879',
        place: 'Trotamundos Terraza',
        urlVideo: '',
        img_url: 'https://res.cloudinary.com/drgcrjsax/image/upload/v1693279342/a54uoirbaqwtyaapkkgi.jpg',
        img_public_id:'a54uoirbaqwtyaapkkgi',
        conditionTerms: true,
        producerId : 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {}),
  
    down: async (queryInterface, Sequelize) => queryInterface.bulkDelete('events', null, {}),
  };
  